import type { Coupon } from "./types";

/** Client-safe coupon fallback; no Node.js or server-only imports. */
export function getDailyShopeeCoupons(): Coupon[] {
  const vnTime = new Date(
    new Date().toLocaleString("en-US", { timeZone: "Asia/Ho_Chi_Minh" }),
  );
  const dateStr = vnTime.toLocaleDateString("vi-VN", {
    day: "2-digit",
    month: "2-digit",
  });

  return [
    {
      id: "shopee-coupon-fb-250k",
      amount: "25%",
      unit: "giảm",
      title: "Shopee — Độc Quyền Facebook (Giảm 250k)",
      condition: `Giảm tối đa 250k · Đơn tối thiểu 150k · HSD hôm nay (${dateStr})`,
      code: "ĐỘC QUYỀN FB",
      color: "blue",
      category: "facebook",
      platform: "Shopee",
      socialType: "facebook",
      badge: "Độc Quyền Facebook",
      usagePercent: 65,
    },
    {
      id: "shopee-coupon-fb-50k",
      amount: "20%",
      unit: "giảm",
      title: "Shopee — Độc Quyền Facebook (Giảm 50k)",
      condition: `Giảm tối đa 50k · Đơn tối thiểu 200k · HSD hôm nay (${dateStr})`,
      code: "ĐỘC QUYỀN FB",
      color: "blue",
      category: "facebook",
      platform: "Shopee",
      socialType: "facebook",
      badge: "Độc Quyền Facebook",
      usagePercent: 98,
    },
    {
      id: "shopee-coupon-ig-150k",
      amount: "20%",
      unit: "giảm",
      title: "Shopee — Độc Quyền Instagram",
      condition: `Giảm tối đa 150k · Đơn tối thiểu 150k · HSD hôm nay (${dateStr})`,
      code: "ĐỘC QUYỀN IG",
      color: "pink",
      category: "instagram",
      platform: "Shopee",
      socialType: "instagram",
      badge: "Độc Quyền Instagram",
      usagePercent: 48,
    },
    {
      id: "shopee-coupon-yt-100k",
      amount: "15%",
      unit: "giảm",
      title: "Shopee — Độc Quyền YouTube Shopping",
      condition: `Giảm tối đa 100k · Đơn tối thiểu 150k · HSD hôm nay (${dateStr})`,
      code: "YOUTUBE SHOPPING",
      color: "red",
      category: "youtube",
      platform: "Shopee",
      socialType: "youtube",
      badge: "YouTube Shopping",
      usagePercent: 52,
    },
    {
      id: "shopee-coupon-toan-san-50k",
      amount: "50k",
      unit: "giảm",
      title: "Shopee — Toàn sàn đơn từ 250k",
      condition: `HSD 23:59 hôm nay (${dateStr}) · Áp cùng cashback`,
      code: "SHOPEE50K",
      color: "orange",
      category: "toan_san",
      platform: "Shopee",
      url: "https://shopee.vn/m/ma-giam-gia",
    },
    {
      id: "shopee-coupon-freeship-0d",
      amount: "Free",
      unit: "ship",
      title: "Shopee — Miễn phí vận chuyển toàn quốc",
      condition: "Giảm tối đa 70k · Đơn từ 0đ · Áp dụng mọi phương thức",
      code: "FREESHIP0D",
      color: "green",
      category: "freeship",
      platform: "Shopee",
      url: "https://shopee.vn/m/mien-phi-van-chuyen",
    },
    {
      id: "shopee-coupon-vip-300k",
      amount: "300k",
      unit: "VIP",
      title: "Gói Shopee VIP — Siêu voucher độc quyền",
      condition: "Tiết kiệm đến 300k/tháng · 12 voucher Freeship & Toàn sàn",
      code: "SHOPEEVIP",
      color: "orange",
      category: "vip",
      platform: "Shopee",
      url: "https://shopee.vn/m/goi-ShopeeVIP",
    },
    {
      id: "shopee-coupon-freeship-xtra-50",
      amount: "50%",
      unit: "ship",
      title: "Freeship Xtra — Giảm đến 50% phí ship",
      condition: "Tối đa 30k · Áp dụng sản phẩm gắn nhãn Freeship Xtra",
      code: "SHIPXTRA50",
      color: "green",
      category: "freeship",
      platform: "Shopee",
      url: "https://shopee.vn/m/mien-phi-van-chuyen",
    },
    {
      id: "shopee-coupon-vip-member",
      amount: "50k",
      unit: "giảm",
      title: "Đặc quyền Hội viên Shopee VIP Club",
      condition: "Voucher độc quyền ngày đôi & khung giờ vàng VIP",
      code: "VIPCLUB50",
      color: "orange",
      category: "vip",
      platform: "Shopee",
      url: "https://shopee.vn/m/goi-ShopeeVIP",
    },
    {
      id: "shopee-coupon-live-15",
      amount: "15%",
      unit: "giảm",
      title: "Shopee Live & Video — Giảm sâu",
      condition: "Giảm tối đa 50k · Áp dụng sản phẩm gắn tag Live/Video",
      code: "SHOPEELIVE15",
      color: "black",
      category: "live",
      platform: "Shopee",
      url: "https://shopee.vn/m/shopee-live",
    },
    {
      id: "shopee-coupon-mall-100k",
      amount: "100k",
      unit: "hoàn xu",
      title: "Shopee Mall — Công nghệ & Đời sống chính hãng",
      condition: `Hoàn 10% xu đơn từ 500k · HSD ${dateStr}`,
      code: "MALLHOAN100",
      color: "orange",
      category: "mall",
      platform: "Shopee Mall",
      url: "https://shopee.vn/m/shopee-mall",
    },
    {
      id: "shopee-coupon-dealhoan-30k",
      amount: "30k",
      unit: "giảm",
      title: "Shopee — Đơn hàng đầu tiên & Thành viên mới",
      condition: "Đơn từ 99k · Không giới hạn ngành hàng",
      code: "DEALHOAN30",
      color: "blue",
      category: "toan_san",
      platform: "Shopee",
      url: "https://shopee.vn/m/ma-giam-gia",
    },
    {
      id: "shopee-coupon-live-gold-25",
      amount: "25%",
      unit: "giảm",
      title: "Shopee Live — Khung giờ vàng săn sale",
      condition: `Giảm tối đa 70k đơn từ 150k · Áp dụng hôm nay`,
      code: "LIVEGOLD25",
      color: "black",
      category: "live",
      platform: "Shopee",
      url: "https://shopee.vn/m/shopee-live",
    },
  ];
}
