import type { Coupon } from "./types";

/** Client-safe coupon fallback; no Node.js or server-only imports. */
export function getDailyShopeeCoupons(): Coupon[] {
  const vnTime = new Date(
    new Date().toLocaleString("en-US", { timeZone: "Asia/Ho_Chi_Minh" }),
  );
  const dateStr = vnTime.toLocaleDateString("vi-VN", {
    day: "2-digit",
    month: "2-digit",
  });

  return [
    {
      id: "shopee-coupon-fb-250k",
      amount: "250K",
      unit: "giảm",
      title: "Mã Facebook",
      subtitle: "Giảm đến 250K",
      condition: "Giảm tối đa 250K · Đơn từ 150K",
      code: "FACEBOOK250",
      color: "blue",
      category: "facebook",
      platform: "Shopee",
      socialType: "facebook",
      badge: "ĐỘC QUYỀN",
      usagePercent: 65,
    },
    {
      id: "shopee-coupon-ig-150k",
      amount: "150K",
      unit: "giảm",
      title: "Mã Instagram",
      subtitle: "Giảm đến 150K",
      condition: "Giảm tối đa 150K · Đơn từ 150K",
      code: "INSTAGRAM150",
      color: "pink",
      category: "instagram",
      platform: "Shopee",
      socialType: "instagram",
      badge: "ĐỘC QUYỀN",
      usagePercent: 48,
    },
    {
      id: "shopee-coupon-yt-100k",
      amount: "100K",
      unit: "giảm",
      title: "Mã YouTube",
      subtitle: "Giảm đến 100K",
      condition: "Giảm tối đa 100K · Đơn từ 150K",
      code: "YOUTUBE100",
      color: "red",
      category: "youtube",
      platform: "Shopee",
      socialType: "youtube",
      badge: "ĐỘC QUYỀN",
      usagePercent: 52,
    },
    {
      id: "shopee-coupon-freeship-0d",
      amount: "Free",
      unit: "ship",
      title: "Mã Freeship",
      subtitle: "Miễn phí vận chuyển",
      condition: "Giảm phí ship tới 70K · Áp dụng nhiều đơn",
      code: "FREESHIP0D",
      color: "green",
      category: "freeship",
      platform: "Shopee",
      badge: "TOÀN SÀN",
      url: "https://shopee.vn/m/mien-phi-van-chuyen",
    },
    {
      id: "shopee-coupon-mall-100k",
      amount: "100K",
      unit: "hoàn xu",
      title: "Mã Shopee Mall",
      subtitle: "Chính hãng – Yên tâm mua sắm",
      condition: "Hoàn / giảm đến 100K · Đơn từ 500K",
      code: "MALLHOAN100",
      color: "orange",
      category: "mall",
      platform: "Shopee Mall",
      badge: "SHOPEE MALL",
      url: "https://shopee.vn/m/shopee-mall",
    },
    {
      id: "shopee-coupon-vip-300k",
      amount: "300K",
      unit: "VIP",
      title: "Mã Shopee VIP",
      subtitle: "Đặc quyền thành viên",
      condition: "Nhiều voucher độc quyền theo khung giờ",
      code: "VIPCLUB50",
      color: "orange",
      category: "vip",
      platform: "Shopee",
      badge: "THÀNH VIÊN",
      url: "https://shopee.vn/m/goi-ShopeeVIP",
    },
    {
      id: "shopee-coupon-freeship-xtra-50",
      amount: "50%",
      unit: "ship",
      title: "Mã Freeship Xtra",
      subtitle: "Giảm đến 50% phí ship",
      condition: "Tối đa 30k · Áp dụng sản phẩm gắn nhãn Freeship Xtra",
      code: "SHIPXTRA50",
      color: "green",
      category: "freeship",
      platform: "Shopee",
      badge: "FREESHIP XTRA",
      url: "https://shopee.vn/m/mien-phi-van-chuyen",
    },
    {
      id: "shopee-coupon-vip-member",
      amount: "50k",
      unit: "giảm",
      title: "Shopee VIP Club",
      subtitle: "Đặc quyền Hội viên VIP",
      condition: "Voucher độc quyền ngày đôi & khung giờ vàng VIP",
      code: "VIPCLUB50",
      color: "orange",
      category: "vip",
      platform: "Shopee",
      badge: "THÀNH VIÊN",
      url: "https://shopee.vn/m/goi-ShopeeVIP",
    },
    {
      id: "shopee-coupon-live-15",
      amount: "15%",
      unit: "giảm",
      title: "Shopee Live & Video",
      subtitle: "Giảm sâu đến 15%",
      condition: "Giảm tối đa 50k · Áp dụng sản phẩm gắn tag Live/Video",
      code: "SHOPEELIVE15",
      color: "black",
      category: "live",
      platform: "Shopee",
      badge: "SHOPEE LIVE",
      url: "https://shopee.vn/m/shopee-live",
    },
    {
      id: "shopee-coupon-mall-tech-100k",
      amount: "100k",
      unit: "hoàn xu",
      title: "Mã Shopee Mall",
      subtitle: "Công nghệ & Đời sống chính hãng",
      condition: `Hoàn 10% xu đơn từ 500k · HSD ${dateStr}`,
      code: "MALLHOAN100",
      color: "orange",
      category: "mall",
      platform: "Shopee Mall",
      badge: "SHOPEE MALL",
      url: "https://shopee.vn/m/shopee-mall",
    },
    {
      id: "shopee-coupon-dealhoan-30k",
      amount: "30k",
      unit: "giảm",
      title: "Shopee Khách Mới",
      subtitle: "Đơn đầu & Thành viên mới",
      condition: "Đơn từ 99k · Không giới hạn ngành hàng",
      code: "DEALHOAN30",
      color: "blue",
      category: "toan_san",
      platform: "Shopee",
      badge: "KHÁCH MỚI",
      url: "https://shopee.vn/m/ma-giam-gia",
    },
    {
      id: "shopee-coupon-live-gold-25",
      amount: "25%",
      unit: "giảm",
      title: "Shopee Live Gold",
      subtitle: "Khung giờ vàng săn sale",
      condition: `Giảm tối đa 70k đơn từ 150k · Áp dụng hôm nay`,
      code: "LIVEGOLD25",
      color: "black",
      category: "live",
      platform: "Shopee",
      badge: "GIỜ VÀNG",
      url: "https://shopee.vn/m/shopee-live",
    },
  ];
}
